from pathlib import Path
from html import escape

ROOT = Path(__file__).parent / 'dist'
NAV = [('/', 'Home'), ('/poultry-calcium/', 'Poultry calcium'), ('/applications/', 'Applications'), ('/process/', 'Process'), ('/about/', 'About')]


def layout(route, title, description, content):
    nav = ''.join(f'<a href="{url}"' + (' aria-current="page"' if route == url else '') + f'>{label}</a>' for url, label in NAV)
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#087491">
  <meta name="description" content="{escape(description, quote=True)}">
  <title>{escape(title)} | Bahama Mineral Co.</title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/assets/style.css">
  <link rel="stylesheet" href="/assets/ocean.css">
  <script defer src="/assets/site.js"></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header" id="top">
  <div class="container header-inner">
    <a class="brand" href="/" aria-label="Bahama Mineral Co. home"><img src="/assets/bmc-logo.png" alt="" width="98" height="65"><span class="brand__name">BAHAMA<br>MINERAL CO.</span></a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" aria-label="Open navigation"><span></span><span></span><span></span></button>
    <nav class="primary-nav" id="primary-nav" aria-label="Main navigation">{nav}<a class="nav-contact" href="/contact/"{' aria-current="page"' if route == '/contact/' else ''}>Start a conversation</a></nav>
  </div>
</header>
<main id="main">{content}</main>
<footer class="site-footer">
  <div class="container footer-top">
    <div class="footer-statement"><a class="footer-logo" href="/" aria-label="Bahama Mineral Co. home"><img src="/assets/bmc-logo.png" alt="Bahama Mineral Co." width="210" height="140"></a><h2>Useful material starts<br>with a better question.</h2><a class="text-link text-link--light" href="/contact/">Work with us</a></div>
    <div class="footer-links"><div><h3>Explore</h3><a href="/poultry-calcium/">Poultry calcium</a><a href="/applications/">Applications</a><a href="/process/">Our process</a><a href="/about/">Our company</a></div><div><h3>Connect</h3><a href="/contact/">Contact</a><a href="mailto:amar@bahamamineralcompany.com">amar@bahamamineralcompany.com</a><span>Nassau, The Bahamas</span></div></div>
  </div>
  <div class="container footer-bottom"><span>© 2026 Bahama Mineral Co.</span><span>Developing commercial uses for recovered Bahamian conch shell.</span><a href="#top">Back to top</a></div>
</footer>
</body></html>'''


def write(route, title, description, content):
    path = ROOT / route.strip('/') / 'index.html' if route != '/' else ROOT / 'index.html'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(layout(route, title, description, content), encoding='utf-8')


GALLERY = [
    ('Poultry calcium', 'AGRICULTURE', 'cutout-poultry.webp', 'Coarse shell calcium could give laying hens an additional calcium source alongside complete feed.', '/poultry-calcium/', 'Explore the first product'),
    ('Terrazzo tile', 'DESIGN', 'cutout-terrazzo.webp', 'Visible shell chips could bring the colours of conch into terrazzo-style tiles and finishes.', '/applications/#architecture', 'Explore design materials'),
    ('Toothpaste minerals', 'PERSONAL CARE', 'cutout-toothpaste.webp', 'Refined calcium carbonate could be an ingredient in oral care formulations after purification and product testing.', '/applications/#toothpaste', 'Explore oral care'),
    ('Soil amendment', 'AGRICULTURE', 'cutout-soil.webp', 'Finely ground shell could help correct acidic soils where a soil test shows a need.', '/applications/#soil', 'Explore soil uses'),
    ('Biomedical calcium', 'RESEARCH', 'cutout-biomedical.webp', 'Research has shown a route from conch shell to calcium materials; medical use needs extensive validation and approval.', '/applications/#biomedical', 'Explore research'),
    ('Landscape shell', 'OUTDOOR DESIGN', 'cutout-landscape.webp', 'Graded shell chips could bring a pale coastal texture to paths, borders and ground cover.', '/applications/#landscape', 'Explore landscapes'),
    ('Filtration media', 'WATER SYSTEMS', 'cutout-filtration.webp', 'Graded shell is a possible media for selected water treatment designs, subject to application testing.', '/applications/#filtration', 'Explore filtration'),
    ('Composite filler', 'MATERIALS', 'cutout-composite.webp', 'Fine shell powder could be blended into selected composite materials and printed products.', '/applications/#composites', 'Explore composites'),
]


def gallery_markup():
    tabs = []
    panels = []
    count = len(GALLERY) + 1
    for index, (title, category, asset, description, link, action) in enumerate(GALLERY):
        number = f'{index + 1:02d}'
        tabs.append(f'<button class="possibility-tab" type="button" role="tab" id="possibility-tab-{index}" aria-controls="possibility-panel-{index}" aria-selected="{str(index == 0).lower()}" tabindex="{0 if index == 0 else -1}"><span>{number}</span>{title}</button>')
        panels.append(f'<article class="possibility-panel" role="tabpanel" id="possibility-panel-{index}" aria-labelledby="possibility-tab-{index}" {"" if index == 0 else "hidden"}><div class="possibility-art possibility-art--{index % 4}"><img src="/assets/{asset}" alt="{title} material or product cutout" loading="lazy"></div><div class="possibility-copy"><span class="possibility-index">{number} / {count:02d} &nbsp;·&nbsp; {category}</span><h3>{title}</h3><p>{description}</p><a class="text-link" href="{link}">{action} <span aria-hidden="true">↗</span></a></div></article>')
    index = len(GALLERY)
    tabs.append(f'<button class="possibility-tab" type="button" role="tab" id="possibility-tab-{index}" aria-controls="possibility-panel-{index}" aria-selected="false" tabindex="-1"><span>09</span>And more</button>')
    panels.append(f'<article class="possibility-panel" role="tabpanel" id="possibility-panel-{index}" aria-labelledby="possibility-tab-{index}" hidden><div class="possibility-art possibility-art--more"><img src="/assets/conch-cutout.png" alt="Queen conch shell" loading="lazy"></div><div class="possibility-copy"><span class="possibility-index">09 / 09 &nbsp;·&nbsp; OPEN HORIZONS</span><h3>And more.</h3><p>Different grades open different doors. Tell us where shell could work in your product or project.</p><a class="text-link" href="/contact/">Start a conversation <span aria-hidden="true">↗</span></a></div></article>')
    return '<div class="possibility-explorer"><div class="possibility-stage">' + ''.join(panels) + '<div class="possibility-controls"><button type="button" class="possibility-prev" aria-label="Previous use">←</button><span class="possibility-progress">01 / 09</span><button type="button" class="possibility-next" aria-label="Next use">→</button></div></div><div class="possibility-tabs" role="tablist" aria-label="Shell uses">' + ''.join(tabs) + '</div></div>'


def award_roadmap():
    return '''<div class="award-roadmap">
      <div class="award-roadmap__steps" role="tablist" aria-label="BMC milestones">
        <button type="button" role="tab" id="award-tab-tdc" aria-controls="award-panel-tdc" aria-selected="true" tabindex="0"><span>01</span><strong>Tourism Development Corporation</strong><small>$10,000 Economic Innovation award</small></button>
        <button type="button" role="tab" id="award-tab-sbdc" aria-controls="award-panel-sbdc" aria-selected="false" tabindex="-1"><span>02</span><strong>SBDC Bahamas</strong><small>$10,000 Blue Economy Accelerator grant</small></button>
      </div>
      <div class="award-roadmap__panels">
        <figure role="tabpanel" id="award-panel-tdc" aria-labelledby="award-tab-tdc"><img src="/assets/tdc-award.webp" alt="Amar and Alex Pearson at the Tourism Development Corporation award presentation" loading="lazy"><figcaption>Economic Innovation Pitch award · TDC</figcaption></figure>
        <figure role="tabpanel" id="award-panel-sbdc" aria-labelledby="award-tab-sbdc" hidden><img src="/assets/sbdc-award.webp" alt="Alex Pearson with the SBDC Bahamas Blue Economy Accelerator grant award" loading="lazy"><figcaption>Blue Economy Accelerator grant · SBDC Bahamas</figcaption></figure>
      </div>
    </div>'''


home = '''
<section class="home-hero ocean-hero">
  <div class="home-hero__copy"><div class="home-hero__copy-inner">
    <p class="eyebrow eyebrow--gold"><span class="line-dot"></span> BORN IN THE BAHAMAS · BUILT FROM CONCH SHELL</p>
    <h1>The shell was <em>never</em> the end.</h1>
    <p class="hero-lede">Bahama Mineral Co. is giving discarded conch shell a new purpose, developing materials for agriculture, design and other commercial uses.</p>
    <div class="button-row"><a class="button button--gold" href="#products">Explore the possibilities</a><a class="button button--ghost" href="/about/">Meet BMC</a></div>
  </div></div>
  <div class="home-hero__visual"><img src="/assets/conch-cutout.png" alt="Queen conch shell" fetchpriority="high"></div>
</section>
<section class="section pathways" id="products"><div class="container"><div class="section-heading"><div><p class="eyebrow">THE POSSIBILITIES</p><h2>What could one<br><span class="muted">shell become?</span></h2></div><p>One material, many directions. Select a use to see what different grades of conch shell could become. Poultry calcium is our first focus.</p></div>
  __GALLERY__
</div></section>
<section class="section material-intro"><div class="container material-intro__inner"><p class="eyebrow">AN OVERLOOKED LOCAL RESOURCE</p><h2>Conch is iconic.<br><span class="muted">The shell has more to give.</span></h2><div class="intro-columns"><p>Across The Bahamas, conch shell remains after the meat is removed. Much of it has limited commercial use and can accumulate around docks, coastlines and disposal areas.</p><p>We are building the equipment, products and supply relationships to turn that familiar material into considered inputs for agriculture and other markets.</p></div><a class="text-link" href="/about/">Why we started</a></div></section>
<section class="image-story"><div class="image-story__photo"><img src="/assets/conch-recovery.webp" alt="Conch shells beside a Bahamian coastal landing" loading="lazy"></div><div class="image-story__panel"><h2>Recover.<br>Prepare.<br>Prove the use.</h2><p>There is more in a conch shell than the meal it leaves behind. We are bringing that material into new uses, beginning with a local calcium source for poultry and exploring where else it could belong.</p><a class="button button--outline-light" href="/process/">See our approach</a></div></section>
<section class="section story-preview"><div class="container"><div class="story-preview__heading"><div><p class="eyebrow eyebrow--gold">OUR STORY IN PROGRESS</p><h2>From a local idea<br>to real momentum.</h2></div><div><p>Two $10,000 awards have helped us move forward: one from the Tourism Development Corporation and another through SBDC Bahamas’ Blue Economy Accelerator, delivered with The Nature Conservancy and supported by the Global Fund for Coral Reefs.</p><a class="text-link text-link--light" href="/about/">Meet the people behind BMC <span aria-hidden="true">↗</span></a></div></div>__AWARD_ROADMAP__</div></section>
<section class="section next-step"><div class="container next-step__inner"><div><p class="eyebrow">BUILD WITH US</p><h2>Have shell, a use case,<br>or a supply question?</h2></div><div><p>We are speaking with shell sources, poultry farmers, agricultural suppliers, designers, researchers and commercial partners.</p><a class="button button--dark" href="/contact/">Start a conversation</a></div></div></section>
'''

home = home.replace('__GALLERY__', gallery_markup()).replace('__AWARD_ROADMAP__', award_roadmap())

poultry = '''
<section class="page-hero product-hero"><div class="container page-hero__grid"><div><p class="eyebrow">POULTRY CALCIUM · IN DEVELOPMENT</p><h1>From conch shell to a new kind of calcium source.</h1><p class="page-lede">We are developing supplemental calcium for laying poultry from recovered Bahamian conch shell.</p><div class="button-row"><a class="button button--dark" href="/contact/?interest=poultry">Register interest</a><span class="page-hero__note">Pre-commercial · testing and validation ahead</span></div></div><div class="product-hero__visual"><div class="product-hero__halo" aria-hidden="true"></div><img src="/assets/poultry-bag.webp" alt="Bahama Mineral Co. poultry calcium packaging"></div></div></section>
<section class="section egg-context"><div class="container"><div class="section-heading"><div><p class="eyebrow">WHY LOCAL EGGS MATTER</p><h2>Food security<br>starts upstream.</h2></div><p>When egg supply is disrupted, island markets feel it. Building more local capacity also means building dependable local inputs for the farmers producing those eggs.</p></div><div class="egg-context__grid"><div><span>01 / GLOBAL</span><h3>Supply can shift fast.</h3><p>Avian influenza outbreaks have reduced laying flocks and tightened egg supply in major markets.</p></div><div><span>02 / CARIBBEAN</span><h3>A regional priority.</h3><p>CARICOM has identified poultry and table eggs among its food security priorities.</p></div><div><span>03 / THE BAHAMAS</span><h3>More grown at home.</h3><p>National investment in local egg production aims to reduce reliance on imported eggs.</p></div></div><p class="egg-context__sources">Background: <a href="https://ers.usda.gov/data-products/charts-of-note/112677" target="_blank" rel="noopener">USDA</a> · <a href="https://caricom.org/significant-investment-opportunities-in-regions-poultry-industry/" target="_blank" rel="noopener">CARICOM</a> · <a href="https://opm.gov.bs/budget-2025-26-expanding-opportunities-island-by-island-communication-to-parliament-from-prime-minister-and-minister-of-finance-the-hon-philip-edward-davis-kc-mp/" target="_blank" rel="noopener">Office of the Prime Minister</a></p></div></section>
<section class="hen-story"><img src="/assets/hens.webp" alt="Three laying hens in a small tropical poultry yard" loading="lazy"><div class="hen-story__caption"><span>THE LAYING FLOCK</span><p>Every egg begins with a healthy hen and the right nutrition.</p></div></section>
<section class="section"><div class="container split-section"><div class="split-section__lead"><p class="eyebrow">WHY CALCIUM</p><h2>A daily need<br>for laying hens.</h2></div><div class="split-section__body"><p>Hens use calcium to form eggshells. Alongside a complete layer diet, a separate coarse calcium source can help give the flock access to what it needs as eggs are formed.</p><p>We plan to turn recovered Bahamian conch shell into a dependable local calcium input for poultry keepers, farms and feed suppliers. That is one practical piece of a stronger egg supply chain at home.</p><div class="inline-callout">Supplemental calcium for layers, alongside complete feed.</div></div></div></section>
<section class="section product-specs"><div class="container"><div class="section-heading"><div><p class="eyebrow">PRODUCT PROFILE</p><h2>Built for the flock.<br><span class="muted">Rooted in The Bahamas.</span></h2></div><p>Our first intended product is a coarse shell calcium material for laying poultry, developed from recovered conch shell.</p></div><div class="spec-grid"><div><span>INTENDED USE</span><strong>Supplemental calcium for laying poultry</strong></div><div><span>SOURCE MATERIAL</span><strong>Recovered Bahamian conch shell</strong></div><div><span>PLANNED FORM</span><strong>Coarse graded shell material</strong></div><div><span>LOCAL ROLE</span><strong>A Bahamian input for egg producers</strong></div><div><span>FEEDING GUIDANCE</span><strong>To be published before release</strong></div><div><span>AVAILABILITY</span><strong>In development; interest welcome</strong></div></div></div></section>
<section class="section format-section"><div class="container"><div class="format-layout"><div><p class="eyebrow">FORMATS UNDER CONSIDERATION</p><h2>From backyard<br>flocks to buyers.</h2><p>We are shaping useful pack sizes for poultry keepers, farms, feed stores and volume buyers.</p></div><div class="format-display"><img src="/assets/poultry-formats.webp" alt="Four possible poultry calcium bag sizes, from a small pouch to a bulk sack" loading="lazy"></div></div><div class="format-grid"><div><strong>5<span>lb</span></strong><span>Small flock</span></div><div><strong>25<span>lb</span></strong><span>Farm size</span></div><div><strong>50<span>lb</span></strong><span>Commercial size</span></div><div><strong>Bulk</strong><span>Volume buyers</span></div></div></div></section>
<section class="section"><div class="container audience-layout"><div><p class="eyebrow">JOIN THE CONVERSATION</p><h2>Help shape<br>the first release.</h2><p>Tell us what your flock or business needs. Your input can help shape formats and supply planning.</p><a class="button button--dark audience-whatsapp" href="https://wa.me/12425659382?text=Hi%20Amar%2C%20I%27m%20interested%20in%20BMC%20poultry%20calcium." target="_blank" rel="noopener">Message Amar on WhatsApp ↗</a></div><div class="audience-list"><div><span>01</span><h3>Poultry keepers</h3><p>Tell us your flock size and how you currently source calcium.</p></div><div><span>02</span><h3>Farms & feed stores</h3><p>Discuss repeat volume, pack sizes and distribution needs.</p></div><div><span>03</span><h3>Commercial buyers</h3><p>Share your island and expected purchasing patterns.</p></div></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><p class="eyebrow eyebrow--gold">POULTRY CALCIUM</p><h2>Interested in the first product?</h2><p>Tell us about your flock or business. Your input helps inform testing, formats and supply planning.</p></div><a class="button button--gold" href="https://wa.me/12425659382?text=Hi%20Amar%2C%20I%27m%20interested%20in%20BMC%20poultry%20calcium." target="_blank" rel="noopener">Message us on WhatsApp ↗</a></div></section>
'''

def more_applications():
    ids = {'Terrazzo tile': ('terrazzo', 'design'), 'Toothpaste minerals': ('toothpaste', 'personal-care'), 'Soil amendment': ('soil', 'agriculture'), 'Biomedical calcium': ('biomedical', 'research'), 'Filtration media': ('filtration', 'research'), 'Composite filler': ('composites', 'design')}
    cards = []
    for title, category, asset, description, _, _ in GALLERY:
        if title not in ids:
            continue
        cards.append(f'<article class="extra-application" id="{ids[title][0]}"><div class="extra-application__image"><img src="/assets/{asset}" alt="{title} material or product cutout" loading="lazy"></div><div class="extra-application__copy"><span>{category}</span><h3>{title}</h3><p>{description}</p><a href="/contact/?interest={ids[title][1]}" class="text-link">Discuss this direction <span aria-hidden="true">↗</span></a></div></article>')
    return '<section class="section further-applications"><div class="container"><div class="section-heading"><div><p class="eyebrow">MORE POSSIBILITIES</p><h2>One material.<br><span class="muted">More directions.</span></h2></div><p>Some uses are close to familiar shell materials; others call for specialist processing and approvals. We are exploring the routes where the material makes sense.</p></div><div class="extra-applications-grid">' + ''.join(cards) + '</div></div></section>'


applications = '''
<section class="page-hero page-hero--dark applications-hero"><div class="container page-hero__grid"><div><p class="eyebrow eyebrow--gold">02 / APPLICATIONS</p><h1>One shell.<br>Different<br>directions.</h1></div><div class="page-hero__aside"><p>Different grades of processed shell may serve different markets. Each pathway needs the right testing, specifications and demand before it becomes a commercial product.</p><span class="small-rule"></span><span>FIRST FOCUS: POULTRY CALCIUM</span></div></div><img class="applications-hero__shell" src="/assets/conch-cutout.png" alt="" aria-hidden="true"></section>
<section class="applications-list">
  <article class="application-row" id="agriculture"><div class="container application-row__grid"><div class="application-row__meta"><span>AGRICULTURE</span><span class="status">FIRST FOCUS</span></div><div><h2>Poultry calcium</h2><p>Our first intended product is a supplemental calcium material for laying hens. We are developing it from recovered conch shell and validating the material before commercial release.</p><a class="text-link" href="/poultry-calcium/">Explore poultry calcium</a></div><div class="application-row__visual"><img src="/assets/poultry-bag.webp" alt="BMC poultry calcium bag" loading="lazy"></div><div class="application-row__foot">FARMERS · FEED STORES · DISTRIBUTORS</div></div></article>
  <article class="application-row application-row--sand" id="landscape"><div class="container application-row__grid"><div class="application-row__meta"><span>LANDSCAPING</span><span class="status">PLANNED</span></div><div><h2>Landscape &<br>decorative shell</h2><p>Graded shell has visual potential in garden paths, ground cover, borders and outdoor design. Suitability for particular surfaces and conditions would be established through trials.</p><a class="text-link" href="/contact/?interest=landscape">Discuss an application</a></div><div class="application-row__visual"><img src="/assets/landscape-bag.webp" alt="BMC landscape shell bag" loading="lazy"></div><div class="application-row__foot">DESIGNERS · LANDSCAPERS · HOSPITALITY</div></div></article>
  <article class="application-row" id="architecture"><div class="container application-row__grid"><div class="application-row__meta"><span>ARCHITECTURE</span><span class="status">UNDER EVALUATION</span></div><div><h2>Shell as a<br>design material</h2><p>Shell fragments are being explored as a visible aggregate for terrazzo-style surfaces, exposed finishes and other selected non-structural applications. Material and finish performance remain to be tested.</p><a class="text-link" href="/contact/?interest=design">Start a design conversation</a></div><div class="application-row__visual"><img src="/assets/aggregate-bag.webp" alt="Shell aggregate bag and loose shell chips" loading="lazy"></div><div class="application-row__foot">ARCHITECTS · MAKERS · DESIGNERS</div></div></article>
  <article class="application-row application-row--sand" id="bulk"><div class="container application-row__grid"><div class="application-row__meta"><span>BULK MATERIAL</span><span class="status">FUTURE PATHWAY</span></div><div><h2>Larger-volume<br>uses</h2><p>Processed shell may have roles in selected bulk and construction-adjacent applications. Technical testing and any relevant approvals would come before a product specification or structural claim.</p><a class="text-link" href="/contact/?interest=bulk">Discuss a material need</a></div><div class="application-row__visual application-row__visual--bulk"><img src="/assets/conch-recovery.webp" alt="Discarded conch shell at a coastal landing" loading="lazy"></div><div class="application-row__foot">PROJECT BUYERS · COMMERCIAL PARTNERS</div></div></article>
</section>
__EXTRA_APPS__
<section class="section material-note"><div class="container material-note__inner"><div><p class="eyebrow eyebrow--gold">OUR STANDARD</p><h2>The use determines<br>the grade.</h2></div><div><p>Fine, medium and coarse are useful ways to describe possible outputs. Exact particle specifications, performance claims and commercial availability will follow application-specific testing.</p><a class="button button--outline-light" href="/process/">How we approach the process</a></div></div></section>
'''
applications = applications.replace('__EXTRA_APPS__', more_applications())

process = '''
<section class="page-hero process-hero"><div class="container process-hero__grid"><div><p class="eyebrow">OUR PROCESS</p><h1>From discarded shell to material with a purpose.</h1><p class="page-lede">A disciplined operating flow matters more than a good story. We are building the steps that can make shell material consistent, testable and fit for a specific use.</p></div><div class="process-hero__visual"><img src="/assets/conch-recovery.webp" alt="Conch shells at a Bahamian coastal landing"></div></div></section>
<section class="process-flow"><div class="container"><div class="process-row"><span class="process-row__number">01</span><div><span class="eyebrow">INPUT</span><h2>Recover</h2></div><p>Develop shell supply relationships with fisheries, food-service operators and recovery partners. Reliable sourcing starts with knowing the input stream.</p></div><div class="process-row"><span class="process-row__number">02</span><div><span class="eyebrow">PREPARATION</span><h2>Prepare</h2></div><p>Clean and reduce shell material as production capacity is established, with handling appropriate to the intended downstream use.</p></div><div class="process-row"><span class="process-row__number">03</span><div><span class="eyebrow">MATERIAL CONTROL</span><h2>Grade</h2></div><p>Screen material into particle-size ranges that can be evaluated against different product requirements.</p></div><div class="process-row"><span class="process-row__number">04</span><div><span class="eyebrow">EVIDENCE</span><h2>Validate</h2></div><p>Use laboratory work, product trials and relevant technical checks to support specifications and application claims.</p></div><div class="process-row"><span class="process-row__number">05</span><div><span class="eyebrow">MARKET FIT</span><h2>Develop</h2></div><p>Match validated outputs to buyer needs, formats and distribution channels. Expand only where the product and market justify it.</p></div></div></section>
<section class="section process-truth"><div class="container process-truth__grid"><div><p class="eyebrow eyebrow--gold">BUILT FOR USE</p><h2>A local resource.<br>A useful future.</h2></div><div><p>We see a place for Bahamian shell in everyday products. Poultry calcium is our first focus, with other uses to follow where the material, the testing and the people who need it come together.</p><a class="button button--gold" href="/contact/">Discuss a partnership</a></div></div></section>
<section class="section faq-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">COMMON QUESTIONS</p><h2>Good materials<br>need good answers.</h2></div></div><div class="faq-list"><details><summary>Are BMC products available to purchase now?</summary><p>Not yet. Bahama Mineral Co. is pre-commercial. We are developing poultry calcium as the first intended product and welcome expressions of interest from potential buyers.</p></details><details><summary>Does every application use the same material grade?</summary><p>No. Particle size, preparation and testing depend on the intended use. We will publish specifications only when a product pathway has been validated.</p></details><details><summary>Are construction uses approved?</summary><p>No structural or building-code claims are being made. Any construction-related use would require the relevant technical testing and approvals before commercial release.</p></details><details><summary>Can we discuss shell supply or a pilot?</summary><p>Yes. We welcome conversations with shell sources, researchers, farmers, designers and commercial partners while the operating system is being developed.</p></details></div></div></section>
'''

about = '''
<section class="page-hero about-hero"><div class="container page-hero__grid"><div><p class="eyebrow eyebrow--gold">ABOUT BMC</p><h1>Made for<br>the material.<br>Built in The<br>Bahamas.</h1></div><div class="page-hero__aside"><p>Bahama Mineral Co. is a Bahamian materials company developing commercial uses for discarded conch shell and, over time, other overlooked local materials.</p><span class="small-rule"></span><span>NASSAU, THE BAHAMAS</span></div></div></section>
<section class="about-photo"><img src="/assets/conch-recovery.webp" alt="Conch shells at a Bahamian coastal landing"><div class="container about-photo__caption"><span>THE RAW MATERIAL IS FAMILIAR. THE WORK IS TO GIVE IT A USE.</span></div></section>
<section class="section"><div class="container story-grid"><div><p class="eyebrow">WHY WE STARTED</p><h2>We kept seeing<br>the same material<br>left behind.</h2></div><div><p>Conch is woven into daily life in The Bahamas. Once the meat is removed, much of the shell has limited commercial use. We started Bahama Mineral Co. with a practical question: could more of that material be processed and used here?</p><p>We are building from the answer, one validated product pathway at a time. Poultry calcium is the first focus; other applications will follow where the material and market support them.</p><blockquote>“Make useful products here, from material already here.”</blockquote></div></div></section>
<section class="section founders-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">THE FOUNDERS</p><h2>People behind<br>the process.</h2></div><p>Alex and Amar Pearson are building the operating and commercial foundations for Bahama Mineral Co.</p></div><div class="founder-grid"><div class="founder-card"><div class="founder-card__portrait founder-card__portrait--alex"><img src="/assets/alex-pearson.webp" alt="Portrait of Alex Pearson" loading="lazy"><span>01 / 02</span></div><div><span>CO-FOUNDER</span><h3>Alex Pearson</h3><p>Operations, product development and business planning.</p></div></div><div class="founder-card"><div class="founder-card__portrait founder-card__portrait--amar"><img src="/assets/amar-pearson.webp" alt="Portrait of Amar Pearson" loading="lazy"><span>02 / 02</span></div><div><span>CO-FOUNDER</span><h3>Amar Pearson</h3><p>Commercial strategy, partnerships and market development.</p></div></div></div></div></section>
<section class="section progress-section"><div class="container"><div class="story-preview__heading"><div><p class="eyebrow eyebrow--gold">OUR STORY</p><h2>Rooted here.<br>Moving forward.</h2></div><div><p>BMC has received a $10,000 Economic Innovation award from the Tourism Development Corporation and a $10,000 grant through SBDC Bahamas’ Blue Economy Accelerator. The accelerator is a partnership with The Nature Conservancy, supported by the Global Fund for Coral Reefs.</p><p>These milestones have helped us develop the work behind our first product and build connections for the next stage.</p></div></div>__AWARD_ROADMAP__</div></section>
<section class="section next-step"><div class="container next-step__inner"><div><p class="eyebrow">BUILD WITH US</p><h2>Local material.<br>Commercial intent.</h2></div><div><p>We welcome conversations with buyers, shell suppliers, farmers, researchers and partners who see a practical use for this resource.</p><a class="button button--dark" href="/contact/">Start a conversation</a></div></div></section>
'''

about = about.replace('__AWARD_ROADMAP__', award_roadmap())

contact = '''
<section class="page-hero contact-hero"><div class="container page-hero__grid"><div><p class="eyebrow">CONTACT</p><h1>Let's talk<br>about the<br>material.</h1></div><div class="page-hero__aside"><p>Tell us what you need, what material you have, or the application you are exploring. Specific details help us have a useful first conversation.</p><span class="small-rule"></span><a class="text-link" href="mailto:amar@bahamamineralcompany.com">amar@bahamamineralcompany.com</a></div></div></section>
<section class="section contact-content"><div class="container contact-grid"><div class="contact-sidebar"><p class="eyebrow">REASONS TO REACH OUT</p><div><span>01</span><h3>Poultry & agriculture</h3><p>Flock size, calcium needs, projected volume or distribution interest.</p></div><div><span>02</span><h3>Shell supply</h3><p>Where your shell comes from, approximate quantity and location.</p></div><div><span>03</span><h3>Design & materials</h3><p>Intended application, grade, timeline and technical requirements.</p></div><div><span>04</span><h3>Partnerships</h3><p>Research, funding, operations or commercial collaboration.</p></div></div><div class="contact-form-wrap"><p class="eyebrow">START AN INQUIRY</p><h2>Put the useful details<br>in one place.</h2><p class="form-intro">This form prepares an email in your device's mail app. Review and send it from there.</p><form id="inquiry-form"><div class="field-row"><label>Full name <span>*</span><input name="name" autocomplete="name" required></label><label>Email <span>*</span><input name="email" type="email" autocomplete="email" required></label></div><div class="field-row"><label>Organization<input name="organization" autocomplete="organization"></label><label>Island / location<input name="location" autocomplete="address-level2"></label></div><label>What is this about? <span>*</span><select name="interest" required><option value="">Select a topic</option><option value="Poultry calcium">Poultry calcium</option><option value="Agriculture / soil">Agriculture / soil</option><option value="Personal care">Personal care</option><option value="Materials research">Materials research</option><option value="Shell supply">Shell supply</option><option value="Landscape materials">Landscape materials</option><option value="Design / architecture">Design / architecture</option><option value="Bulk material">Bulk material</option><option value="Research / partnership">Research / partnership</option><option value="Other">Other</option></select></label><label>Tell us more <span>*</span><textarea name="message" rows="6" placeholder="Include estimated volume, application, island or timeline where relevant." required></textarea></label><div class="form-actions"><button class="button button--dark" type="submit">Open email draft</button><span>No information is sent until you send the email.</span></div></form></div></div></section>
'''

write('/', 'Commercial Materials From Bahamian Conch Shell', 'Bahama Mineral Co. is developing useful commercial materials from recovered Bahamian conch shell, starting with poultry calcium.', home)
write('/poultry-calcium/', 'Poultry Calcium in Development', 'A locally processed supplemental calcium material for laying poultry, being developed from recovered Bahamian conch shell.', poultry)
write('/applications/', 'Conch Shell Applications', 'Explore potential uses for Bahamian conch shell, from poultry calcium and terrazzo to oral care, soil, filtration and composite materials.', applications)
write('/process/', 'Our Materials Process', 'See how Bahama Mineral Co. plans to recover, prepare, grade and validate Bahamian conch shell for commercial uses.', process)
write('/about/', 'About Our Company', 'Meet Bahama Mineral Co., a Nassau-based materials company founded by Alex and Amar Pearson.', about)
write('/contact/', 'Contact Us', 'Contact Bahama Mineral Co. about poultry calcium, shell supply, commercial materials, research or partnerships.', contact)
(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\n', encoding='utf-8')
print('Generated 6 pages')
