from pathlib import Path
from html import escape

ROOT = Path(__file__).parent / 'dist'
NAV = [('/', 'Home'), ('/poultry-calcium/', 'Poultry calcium'), ('/applications/', 'Applications'), ('/process/', 'Process'), ('/about/', 'About')]


def layout(route, title, description, content):
    nav = ''.join(f'<a href="{url}"' + (' aria-current="page"' if route == url else '') + f'>{label}</a>' for url, label in NAV)
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#087491">
  <meta name="description" content="{escape(description, quote=True)}">
  <title>{escape(title)} | Bahama Mineral Co.</title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/assets/style.css">
  <link rel="stylesheet" href="/assets/ocean.css">
  <script defer src="/assets/site.js"></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<div class="utility"><div class="container utility__inner"><span>BAHAMIAN MATERIALS COMPANY</span><span>NASSAU, THE BAHAMAS <span class="utility__divider">/</span> PRE-COMMERCIAL DEVELOPMENT</span></div></div>
<header class="site-header" id="top">
  <div class="container header-inner">
    <a class="brand" href="/" aria-label="Bahama Mineral Co. home"><img src="/assets/bmc-logo.png" alt="" width="98" height="65"><span class="brand__name">BAHAMA<br>MINERAL CO.</span></a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" aria-label="Open navigation"><span></span><span></span><span></span></button>
    <nav class="primary-nav" id="primary-nav" aria-label="Main navigation">{nav}<a class="nav-contact" href="/contact/"{' aria-current="page"' if route == '/contact/' else ''}>Start a conversation</a></nav>
  </div>
</header>
<main id="main">{content}</main>
<footer class="site-footer">
  <div class="container footer-top">
    <div class="footer-statement"><p class="eyebrow eyebrow--gold">BAHAMA MINERAL CO.</p><h2>Useful material starts<br>with a better question.</h2><a class="text-link text-link--light" href="/contact/">Work with us</a></div>
    <div class="footer-links"><div><h3>Explore</h3><a href="/poultry-calcium/">Poultry calcium</a><a href="/applications/">Applications</a><a href="/process/">Our process</a><a href="/about/">Our company</a></div><div><h3>Connect</h3><a href="/contact/">Contact</a><a href="mailto:info@soilgold.bs">info@soilgold.bs</a><span>Nassau, The Bahamas</span></div></div>
  </div>
  <div class="container footer-bottom"><span>© 2026 Bahama Mineral Co.</span><span>Developing commercial uses for recovered Bahamian conch shell.</span><a href="#top">Back to top</a></div>
</footer>
</body></html>'''


def write(route, title, description, content):
    path = ROOT / route.strip('/') / 'index.html' if route != '/' else ROOT / 'index.html'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(layout(route, title, description, content), encoding='utf-8')


home = '''
<section class="home-hero ocean-hero">
  <div class="home-hero__copy"><div class="home-hero__copy-inner">
    <p class="eyebrow eyebrow--gold"><span class="line-dot"></span> BORN IN THE BAHAMAS · BUILT FROM CONCH SHELL</p>
    <h1>The shell was <em>never</em> the end.</h1>
    <p class="hero-lede">Bahama Mineral Co. is giving discarded conch shell a new purpose, developing materials for agriculture, design and other commercial uses.</p>
    <div class="button-row"><a class="button button--gold" href="#products">Explore the possibilities</a><a class="button button--ghost" href="/about/">Meet BMC</a></div>
    <div class="hero-caption-line"><span>RECOVERED IN THE BAHAMAS</span><span>REIMAGINED FOR WHAT COMES NEXT</span></div>
  </div></div>
  <div class="home-hero__visual"><div class="hero-orbit" aria-hidden="true"></div><img src="/assets/conch-cutout.png" alt="Illustrative cutout of a queen conch shell" fetchpriority="high"><div class="hero-float"><span>01 / THE SOURCE</span><strong>One remarkable raw material.</strong></div></div>
</section>
<div class="chapter-bar"><div class="container chapter-bar__inner"><span>ONE SHELL</span><span>POULTRY CALCIUM</span><span>LANDSCAPE</span><span>DESIGN MATERIAL</span><span>FUTURE USES</span></div></div>
<section class="section pathways" id="products"><div class="container"><div class="section-heading"><div><p class="eyebrow">THE PRODUCT POSSIBILITIES</p><h2>What could one<br><span class="muted">shell become?</span></h2></div><p>Three visual product concepts show the direction we are building toward. Poultry calcium is first; each additional use depends on testing and market fit.</p></div>
  <div class="pathway-grid">
    <a class="pathway-card pathway-card--feature" href="/poultry-calcium/"><div class="pathway-card__top"><span>01 / FIRST PRODUCT</span><span class="status status--light">IN DEVELOPMENT</span></div><div class="pathway-card__visual"><img src="/assets/poultry-pack.png" alt="Concept packaging for BMC poultry calcium" loading="lazy"></div><div class="pathway-card__body"><h3>Poultry<br>calcium</h3><p>Supplemental shell calcium being developed for laying hens.</p><span class="pathway-card__action">Explore poultry calcium</span></div></a>
    <a class="pathway-card pathway-card--cream" href="/applications/#landscape"><div class="pathway-card__top"><span>02 / OUTDOOR DESIGN</span><span class="status">PLANNED</span></div><div class="pathway-card__visual"><img src="/assets/landscape-pack.png" alt="Concept packaging for decorative landscape shell" loading="lazy"></div><div class="pathway-card__body"><h3>Landscape<br>shell</h3><p>Graded shell considered for pathways, borders and accents.</p><span class="pathway-card__action">Explore applications</span></div></a>
    <a class="pathway-card pathway-card--sand" href="/applications/#architecture"><div class="pathway-card__top"><span>03 / MATERIAL DESIGN</span><span class="status">UNDER EVALUATION</span></div><div class="pathway-card__visual"><img src="/assets/aggregate-kit.png" alt="Concept sample kit for architectural shell aggregate" loading="lazy"></div><div class="pathway-card__body"><h3>Shell<br>aggregate</h3><p>Visible shell fragments explored for selected decorative finishes.</p><span class="pathway-card__action">Explore applications</span></div></a>
  </div><p class="concept-note">Packaging and product imagery are visual concepts. No BMC product is currently available for purchase.</p>
</div></section>
<section class="section material-intro"><div class="container editorial-grid"><div class="editorial-grid__label"><span class="section-number">02 / THE OPPORTUNITY</span><div class="vertical-rule"></div></div><div class="editorial-grid__body"><p class="eyebrow">AN OVERLOOKED LOCAL RESOURCE</p><h2>Conch is iconic.<br><span class="muted">The shell has more to give.</span></h2><div class="intro-columns"><p>Across The Bahamas, conch shell remains after the meat is removed. Much of it has limited commercial use and can accumulate around docks, coastlines and disposal areas.</p><p>We are building the equipment, products and supply relationships to turn that familiar material into considered inputs for agriculture and other markets.</p></div><a class="text-link" href="/about/">Why we started</a></div></div></section>
<section class="image-story"><div class="image-story__photo"><img src="/assets/conch-recovery.webp" alt="Illustrative scene of discarded conch shells beside a Bahamian coastal landing" loading="lazy"><span class="photo-credit">CONCEPT IMAGE · NOT A BMC COLLECTION SITE</span></div><div class="image-story__panel"><p class="eyebrow eyebrow--gold">THE MATERIAL JOURNEY</p><h2>Recover.<br>Prepare.<br>Prove the use.</h2><p>Particle size, testing and customer need determine where processed shell can make sense. Our first focus is clear. Other applications must earn their place through evidence.</p><a class="button button--outline-light" href="/process/">See our approach</a><div class="image-story__serial">BMC / MATERIAL 001</div></div></section>
<section class="section status-section"><div class="container status-layout"><div><p class="eyebrow eyebrow--gold">WHERE WE ARE TODAY</p><h2>Big vision.<br>Honest stage.</h2><p>We are building toward commercial production and validating the first product before making it available.</p><a class="text-link text-link--light" href="/about/">Our story and progress</a></div><div class="status-list"><div><span>01</span><p>Core processing equipment <strong>purchased and awaiting shipment</strong></p></div><div><span>02</span><p>Initial Nassau production location <strong>secured; site preparation ahead</strong></p></div><div><span>03</span><p>Poultry calcium <strong>in pre-commercial development and validation</strong></p></div><div><span>04</span><p>Conversations open with <strong>farmers, suppliers and commercial buyers</strong></p></div></div></div></section>
<section class="section next-step"><div class="container next-step__inner"><div><p class="eyebrow">BUILD WITH US</p><h2>Have shell, a use case,<br>or a supply question?</h2></div><div><p>We are speaking with shell sources, poultry farmers, agricultural suppliers, designers, researchers and commercial partners.</p><a class="button button--dark" href="/contact/">Start a conversation</a></div></div></section>
'''

poultry = '''
<section class="page-hero product-hero"><div class="container page-hero__grid"><div><p class="eyebrow">01 / FIRST PRODUCT · IN DEVELOPMENT</p><h1>From conch shell to a new kind of calcium source.</h1><p class="page-lede">We are developing supplemental calcium for laying poultry from recovered Bahamian conch shell.</p><div class="button-row"><a class="button button--dark" href="/contact/?interest=poultry">Register interest</a><span class="page-hero__note">Pre-commercial · testing and validation ahead</span></div></div><div class="product-hero__visual"><div class="product-hero__halo" aria-hidden="true"></div><img src="/assets/poultry-pack.png" alt="Concept packaging for Bahama Mineral Co. poultry calcium"><div class="product-hero__stamp"><span>VISUAL PACKAGING CONCEPT<br>NOT AVAILABLE FOR PURCHASE</span><strong>01</strong></div></div></div></section>
<section class="section"><div class="container split-section"><div class="split-section__lead"><p class="eyebrow">WHY POULTRY CALCIUM</p><h2>A specific need.<br>One promising<br>local input.</h2></div><div class="split-section__body"><p>Every egg requires calcium. Supplemental shell calcium is commonly offered alongside a complete layer diet, giving laying birds access to an additional calcium source.</p><p>Our goal is to develop a controlled, locally processed shell material for that established product category. The product is still being tested; final specifications and feeding guidance are not yet published.</p><div class="inline-callout">A supplement to a complete layer diet, not a complete feed.</div></div></div></section>
<section class="section product-specs"><div class="container"><div class="section-heading"><div><p class="eyebrow">PRODUCT PROFILE</p><h2>What we know.<br><span class="muted">What we are validating.</span></h2></div><p>Clear status matters. We are sharing the intended use while keeping unverified specifications open.</p></div><div class="spec-grid"><div><span>INTENDED USE</span><strong>Supplemental calcium for laying poultry</strong></div><div><span>SOURCE MATERIAL</span><strong>Recovered Bahamian conch shell</strong></div><div><span>PLANNED FORM</span><strong>Coarse graded shell material</strong></div><div><span>CALCIUM ANALYSIS</span><strong>Pending laboratory validation</strong></div><div><span>FEEDING GUIDANCE</span><strong>To be published after validation</strong></div><div><span>AVAILABILITY</span><strong>Pre-commercial; expressions of interest open</strong></div></div></div></section>
<section class="section format-section"><div class="container format-layout"><div><p class="eyebrow">FORMATS UNDER CONSIDERATION</p><h2>From backyard<br>flocks to buyers.</h2><p>Package sizes will be finalized after testing, production planning and customer input.</p></div><div class="format-grid"><div><strong>5<span>lb</span></strong><span>Small flock</span></div><div><strong>25<span>lb</span></strong><span>Farm size</span></div><div><strong>50<span>lb</span></strong><span>Commercial size</span></div><div><strong>Bulk</strong><span>Volume buyers</span></div></div></div></section>
<section class="section"><div class="container audience-layout"><div><p class="eyebrow">WHO WE ARE SPEAKING WITH</p><h2>Help shape<br>the first release.</h2></div><div class="audience-list"><div><span>01</span><h3>Poultry keepers</h3><p>Tell us your flock size and how you currently source calcium.</p></div><div><span>02</span><h3>Farms & feed stores</h3><p>Discuss repeat volume, pack sizes and distribution needs.</p></div><div><span>03</span><h3>Commercial buyers</h3><p>Share specifications, island and expected purchasing patterns.</p></div></div></div></section>
<section class="cta-band"><div class="container cta-band__inner"><div><p class="eyebrow eyebrow--gold">POULTRY CALCIUM</p><h2>Interested in the first product?</h2><p>Tell us about your flock or business. Your input helps inform testing, formats and supply planning.</p></div><a class="button button--gold" href="/contact/?interest=poultry">Register your interest</a></div></section>
'''

applications = '''
<section class="page-hero page-hero--dark applications-hero"><div class="container page-hero__grid"><div><p class="eyebrow eyebrow--gold">02 / APPLICATIONS</p><h1>One shell.<br>Different<br>directions.</h1></div><div class="page-hero__aside"><p>Different grades of processed shell may serve different markets. Each pathway needs the right testing, specifications and demand before it becomes a commercial product.</p><span class="small-rule"></span><span>FIRST FOCUS: POULTRY CALCIUM</span></div></div><img class="applications-hero__shell" src="/assets/conch-cutout.png" alt="" aria-hidden="true"></section>
<section class="applications-list">
  <article class="application-row" id="agriculture"><div class="container application-row__grid"><div class="application-row__meta"><span>01 / AGRICULTURE</span><span class="status">FIRST FOCUS</span></div><div><h2>Poultry calcium</h2><p>Our first intended product is a supplemental calcium material for laying hens. We are developing it from recovered conch shell and validating the material before commercial release.</p><a class="text-link" href="/poultry-calcium/">Explore poultry calcium</a></div><div class="application-row__visual"><img src="/assets/poultry-pack.png" alt="Concept packaging for poultry calcium" loading="lazy"><span>VISUAL CONCEPT</span></div><div class="application-row__foot">FARMERS · FEED STORES · DISTRIBUTORS</div></div></article>
  <article class="application-row application-row--sand" id="landscape"><div class="container application-row__grid"><div class="application-row__meta"><span>02 / LANDSCAPING</span><span class="status">PLANNED</span></div><div><h2>Landscape &<br>decorative shell</h2><p>Graded shell has visual potential in garden paths, ground cover, borders and outdoor design. Suitability for particular surfaces and conditions would be established through trials.</p><a class="text-link" href="/contact/?interest=landscape">Discuss an application</a></div><div class="application-row__visual"><img src="/assets/landscape-pack.png" alt="Concept packaging for landscape shell" loading="lazy"><span>VISUAL CONCEPT</span></div><div class="application-row__foot">DESIGNERS · LANDSCAPERS · HOSPITALITY</div></div></article>
  <article class="application-row" id="architecture"><div class="container application-row__grid"><div class="application-row__meta"><span>03 / ARCHITECTURE</span><span class="status">UNDER EVALUATION</span></div><div><h2>Shell as a<br>design material</h2><p>Shell fragments are being explored as a visible aggregate for terrazzo-style surfaces, exposed finishes and other selected non-structural applications. Material and finish performance remain to be tested.</p><a class="text-link" href="/contact/?interest=design">Start a design conversation</a></div><div class="application-row__visual"><img src="/assets/aggregate-kit.png" alt="Concept shell aggregate sample kit" loading="lazy"><span>VISUAL CONCEPT</span></div><div class="application-row__foot">ARCHITECTS · MAKERS · DESIGNERS</div></div></article>
  <article class="application-row application-row--sand" id="bulk"><div class="container application-row__grid"><div class="application-row__meta"><span>04 / BULK MATERIAL</span><span class="status">FUTURE PATHWAY</span></div><div><h2>Larger-volume<br>uses</h2><p>Processed shell may have roles in selected bulk and construction-adjacent applications. Technical testing and any relevant approvals would come before a product specification or structural claim.</p><a class="text-link" href="/contact/?interest=bulk">Discuss a material need</a></div><div class="application-row__visual application-row__visual--bulk"><img src="/assets/conch-recovery.webp" alt="Illustrative pile of discarded conch shell" loading="lazy"><span>ILLUSTRATIVE IMAGE</span></div><div class="application-row__foot">PROJECT BUYERS · COMMERCIAL PARTNERS</div></div></article>
</section>
<section class="section material-note"><div class="container material-note__inner"><div><p class="eyebrow eyebrow--gold">OUR STANDARD</p><h2>The use determines<br>the grade.</h2></div><div><p>Fine, medium and coarse are useful ways to describe possible outputs. Exact particle specifications, performance claims and commercial availability will follow application-specific testing.</p><a class="button button--outline-light" href="/process/">How we approach the process</a></div></div></section>
'''

process = '''
<section class="page-hero process-hero"><div class="container process-hero__grid"><div><p class="eyebrow">03 / PROCESS</p><h1>From discarded shell to material with a purpose.</h1><p class="page-lede">A disciplined operating flow matters more than a good story. We are building the steps that can make shell material consistent, testable and fit for a specific use.</p></div><div class="process-hero__visual"><img src="/assets/conch-recovery.webp" alt="Illustrative Bahamian conch shell recovery scene"><span>ILLUSTRATIVE MATERIAL IMAGE</span></div></div></section>
<section class="process-flow"><div class="container"><div class="process-row"><span class="process-row__number">01</span><div><span class="eyebrow">INPUT</span><h2>Recover</h2></div><p>Develop shell supply relationships with fisheries, food-service operators and recovery partners. Reliable sourcing starts with knowing the input stream.</p></div><div class="process-row"><span class="process-row__number">02</span><div><span class="eyebrow">PREPARATION</span><h2>Prepare</h2></div><p>Clean and reduce shell material as production capacity is established, with handling appropriate to the intended downstream use.</p></div><div class="process-row"><span class="process-row__number">03</span><div><span class="eyebrow">MATERIAL CONTROL</span><h2>Grade</h2></div><p>Screen material into particle-size ranges that can be evaluated against different product requirements.</p></div><div class="process-row"><span class="process-row__number">04</span><div><span class="eyebrow">EVIDENCE</span><h2>Validate</h2></div><p>Use laboratory work, product trials and relevant technical checks to support specifications and application claims.</p></div><div class="process-row"><span class="process-row__number">05</span><div><span class="eyebrow">MARKET FIT</span><h2>Develop</h2></div><p>Match validated outputs to buyer needs, formats and distribution channels. Expand only where the product and market justify it.</p></div></div></section>
<section class="section process-truth"><div class="container process-truth__grid"><div><p class="eyebrow eyebrow--gold">THE CURRENT STAGE</p><h2>Building the line.<br>Testing the case.</h2></div><div><p>Core machinery has been purchased and is awaiting shipment. An initial production location in Nassau is secured and requires preparation. Product testing and validation are the next gates before commercial release.</p><a class="button button--gold" href="/contact/">Discuss a partnership</a></div></div></section>
<section class="section faq-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">COMMON QUESTIONS</p><h2>Good materials<br>need good answers.</h2></div></div><div class="faq-list"><details><summary>Are BMC products available to purchase now?</summary><p>Not yet. Bahama Mineral Co. is pre-commercial. We are developing poultry calcium as the first intended product and welcome expressions of interest from potential buyers.</p></details><details><summary>Does every application use the same material grade?</summary><p>No. Particle size, preparation and testing depend on the intended use. We will publish specifications only when a product pathway has been validated.</p></details><details><summary>Are construction uses approved?</summary><p>No structural or building-code claims are being made. Any construction-related use would require the relevant technical testing and approvals before commercial release.</p></details><details><summary>Can we discuss shell supply or a pilot?</summary><p>Yes. We welcome conversations with shell sources, researchers, farmers, designers and commercial partners while the operating system is being developed.</p></details></div></div></section>
'''

about = '''
<section class="page-hero about-hero"><div class="container page-hero__grid"><div><p class="eyebrow eyebrow--gold">04 / ABOUT BMC</p><h1>Made for<br>the material.<br>Built in The<br>Bahamas.</h1></div><div class="page-hero__aside"><p>Bahama Mineral Co. is a Bahamian materials company developing commercial uses for discarded conch shell and, over time, other overlooked local materials.</p><span class="small-rule"></span><span>NASSAU, THE BAHAMAS</span></div></div></section>
<section class="about-photo"><img src="/assets/conch-recovery.webp" alt="Illustrative Bahamian coastal scene with discarded conch shells"><div class="container about-photo__caption"><span>THE RAW MATERIAL IS FAMILIAR. THE WORK IS TO GIVE IT A USE.</span><span>CONCEPT IMAGE</span></div></section>
<section class="section"><div class="container story-grid"><div><p class="eyebrow">WHY WE STARTED</p><h2>We kept seeing<br>the same material<br>left behind.</h2></div><div><p>Conch is woven into daily life in The Bahamas. Once the meat is removed, much of the shell has limited commercial use. We started Bahama Mineral Co. with a practical question: could more of that material be processed and used here?</p><p>We are building from the answer, one validated product pathway at a time. Poultry calcium is the first focus; other applications will follow where the material and market support them.</p><blockquote>“Make useful products here, from material already here.”</blockquote></div></div></section>
<section class="section founders-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">THE FOUNDERS</p><h2>People behind<br>the process.</h2></div><p>Alex and Amar Pearson are building the operating and commercial foundations for Bahama Mineral Co.</p></div><div class="founder-grid"><div class="founder-card"><div class="founder-card__monogram">AP<span>01</span></div><div><span>CO-FOUNDER</span><h3>Alex Pearson</h3><p>Operations, product development and business planning.</p></div></div><div class="founder-card"><div class="founder-card__monogram">AP<span>02</span></div><div><span>CO-FOUNDER</span><h3>Amar Pearson</h3><p>Commercial strategy, partnerships and market development.</p></div></div></div></div></section>
<section class="section progress-section"><div class="container progress-grid"><div><p class="eyebrow eyebrow--gold">THE WORK UNDERWAY</p><h2>Progress without<br>pretending it is<br>finished.</h2></div><div class="progress-items"><div><span>01</span><p><strong>Capital secured.</strong> Initial $10,000 funding from the Tourism Development Corporation.</p></div><div><span>02</span><p><strong>Equipment purchased.</strong> Core processing machinery is awaiting shipment.</p></div><div><span>03</span><p><strong>Site secured.</strong> The initial Nassau production location requires clearing and preparation.</p></div><div><span>04</span><p><strong>First product in development.</strong> Poultry calcium requires testing and validation before release.</p></div></div></div></section>
<section class="section next-step"><div class="container next-step__inner"><div><p class="eyebrow">BUILD WITH US</p><h2>Local material.<br>Commercial intent.</h2></div><div><p>We welcome conversations with buyers, shell suppliers, farmers, researchers and partners who see a practical use for this resource.</p><a class="button button--dark" href="/contact/">Start a conversation</a></div></div></section>
'''

contact = '''
<section class="page-hero contact-hero"><div class="container page-hero__grid"><div><p class="eyebrow">05 / CONTACT</p><h1>Let's talk<br>about the<br>material.</h1></div><div class="page-hero__aside"><p>Tell us what you need, what material you have, or the application you are exploring. Specific details help us have a useful first conversation.</p><span class="small-rule"></span><a class="text-link" href="mailto:info@soilgold.bs">info@soilgold.bs</a></div></div></section>
<section class="section contact-content"><div class="container contact-grid"><div class="contact-sidebar"><p class="eyebrow">REASONS TO REACH OUT</p><div><span>01</span><h3>Poultry & agriculture</h3><p>Flock size, calcium needs, projected volume or distribution interest.</p></div><div><span>02</span><h3>Shell supply</h3><p>Where your shell comes from, approximate quantity and location.</p></div><div><span>03</span><h3>Design & materials</h3><p>Intended application, grade, timeline and technical requirements.</p></div><div><span>04</span><h3>Partnerships</h3><p>Research, funding, operations or commercial collaboration.</p></div></div><div class="contact-form-wrap"><p class="eyebrow">START AN INQUIRY</p><h2>Put the useful details<br>in one place.</h2><p class="form-intro">This form prepares an email in your device's mail app. Review and send it from there.</p><form id="inquiry-form"><div class="field-row"><label>Full name <span>*</span><input name="name" autocomplete="name" required></label><label>Email <span>*</span><input name="email" type="email" autocomplete="email" required></label></div><div class="field-row"><label>Organization<input name="organization" autocomplete="organization"></label><label>Island / location<input name="location" autocomplete="address-level2"></label></div><label>What is this about? <span>*</span><select name="interest" required><option value="">Select a topic</option><option value="Poultry calcium">Poultry calcium</option><option value="Shell supply">Shell supply</option><option value="Landscape materials">Landscape materials</option><option value="Design / architecture">Design / architecture</option><option value="Bulk material">Bulk material</option><option value="Research / partnership">Research / partnership</option><option value="Other">Other</option></select></label><label>Tell us more <span>*</span><textarea name="message" rows="6" placeholder="Include estimated volume, application, island or timeline where relevant." required></textarea></label><div class="form-actions"><button class="button button--dark" type="submit">Open email draft</button><span>No information is sent until you send the email.</span></div></form></div></div></section>
'''

write('/', 'Commercial Materials From Bahamian Conch Shell', 'Bahama Mineral Co. is developing useful commercial materials from recovered Bahamian conch shell, starting with poultry calcium.', home)
write('/poultry-calcium/', 'Poultry Calcium in Development', 'A locally processed supplemental calcium material for laying poultry, being developed from recovered Bahamian conch shell.', poultry)
write('/applications/', 'Conch Shell Applications', 'Explore Bahama Mineral Co. planned and developing uses for recovered conch shell across agriculture, landscaping and design.', applications)
write('/process/', 'Our Materials Process', 'See how Bahama Mineral Co. plans to recover, prepare, grade and validate Bahamian conch shell for commercial uses.', process)
write('/about/', 'About Our Company', 'Meet Bahama Mineral Co., a Nassau-based materials company founded by Alex and Amar Pearson.', about)
write('/contact/', 'Contact Us', 'Contact Bahama Mineral Co. about poultry calcium, shell supply, commercial materials, research or partnerships.', contact)
(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\n', encoding='utf-8')
print('Generated 6 pages')
